### ISSUE TITLE
Liste contributive des réalisations pour la galerie

### ISSUE THREAD

**Issue by linogaliana** [InseeFrLab/funathon2023#2]
__Modèle à modifier et à nous envoyer dans la suite de cette page pour suggérer des modifications__ : 

```yaml
---
title: "Ma réalisation"
image: https://raw.githubusercontent.com/InseeFrLab/funathon2023_sujet4/main/img/demo_yuka.png
code: https://github.com/InseeFrLab/funathon2023_sujet4
website: https://inseefrlab.github.io/funathon2023_sujet4/
---
```

Les champs à changer sont ainsi les suivants :

- `title` : Le titre de votre réalisation qui apparaitra dans la galerie
- `image`: Une image sympa à mettre en avant
- `code`: Un lien vers le dépôt `Github` ou `Gitlab` de votre projet
- `website`: Eventuellement un lien vers un site web annexe produit par votre réalisation (par exemple si vous avez produit une application)

💡 Si l'image n'est pas disponible à une URL publique (par exemple parce que vous l'avez pas exportée), vous pouvez la copier coller dans cette discussion ou nous l'envoyer sur `Tchap`
